name: CI

on:
  push:
    branches: master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Install JDK
        uses: actions/setup-java@v1
        with:
          # TODO: Multiple Java versions
          java-version: 1.8
      - name: Assemble
        run: cd extracare-gradle-plugin && ./gradlew clean && cd .. && ./gradlew clean assemble --stacktrace
      - name: Check
        run: ./gradlew check --stacktrace
      - name: Build
        run: ./gradlew build --stacktrace
